import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any

import httpx
from sqlalchemy import text
from sqlalchemy.orm import Session
from tenacity import retry, stop_after_attempt, wait_exponential

from app.agents.copilot import MarketingCopilotGraph
from app.core.config import get_settings
from app.domain.models import Campaign, Message, Segment
from app.infrastructure.repositories import CampaignRepository

logger = logging.getLogger(__name__)


def _get_redis_client():
    """Try to get a Redis connection. Returns None if unavailable."""
    try:
        import redis
        settings = get_settings()
        client = redis.from_url(settings.redis_url, decode_responses=True)
        client.ping()
        return client
    except Exception:
        return None


class CampaignService:
    def __init__(self, db: Session):
        self.db = db
        self.repo = CampaignRepository(db)
        self.settings = get_settings()

    def draft_from_goal(self, tenant_id: uuid.UUID, user_id: uuid.UUID | None, goal: str, name: str | None = None) -> Campaign:
        plan = MarketingCopilotGraph(self.db).plan(tenant_id, goal)
        segment = Segment(
            tenant_id=tenant_id,
            name=f"AI audience - {goal[:48]}",
            description="Generated by copilot from marketer business goal.",
            source="ai_generated",
            filters={
                **plan["segment"]["filters"],
                "params": {key: str(value) for key, value in plan["segment"]["params"].items()},
            },
            sql_text=plan["segment"]["sql_text"],
            estimated_size=plan["audience_size"],
            created_by=user_id,
        )
        self.db.add(segment)
        self.db.flush()
        campaign = Campaign(
            tenant_id=tenant_id,
            segment_id=segment.id,
            name=name or f"Copilot campaign - {goal[:40]}",
            goal=goal,
            channels=plan["strategy"]["channels"],
            strategy={**plan["strategy"], "explainability": plan["explainability"]},
            variants=plan["variants"],
            created_by=user_id,
        )
        return self.repo.create(campaign)

    def launch(self, campaign_id: uuid.UUID, limit: int = 1000) -> dict[str, Any]:
        campaign = self.repo.get(campaign_id)
        if not campaign or not campaign.segment:
            raise ValueError("Campaign or segment not found")
        params = {key: self._coerce(value) for key, value in campaign.segment.filters.get("params", {}).items()}
        rows = self.db.execute(text(campaign.segment.sql_text + " LIMIT :limit"), {**params, "limit": limit}).mappings().all()

        # Determine A/B split weights from strategy
        ab_test = campaign.strategy.get("ab_test", {})
        splits = ab_test.get("split", [])
        num_variants = max(len(campaign.variants), 1)

        # Build variant weight boundaries for proper A/B split
        if splits and len(splits) == num_variants and sum(splits) == 100:
            # Use strategy-defined split weights
            cumulative = []
            total = 0
            for s in splits:
                total += s
                cumulative.append(total)
        else:
            # Equal split fallback
            cumulative = [((i + 1) * 100) // num_variants for i in range(num_variants)]

        messages: list[Message] = []
        for index, row in enumerate(rows):
            customer_id = row["id"]
            channel = campaign.channels[index % max(len(campaign.channels), 1)]

            # A/B split: assign variant based on position in the split
            pct_position = ((index * 100) // max(len(rows), 1))
            variant_idx = 0
            for ci, threshold in enumerate(cumulative):
                if pct_position < threshold:
                    variant_idx = ci
                    break
            else:
                variant_idx = num_variants - 1

            variant = campaign.variants[variant_idx % num_variants]
            msg = Message(
                tenant_id=campaign.tenant_id,
                campaign_id=campaign.id,
                customer_id=customer_id,
                channel=channel,
                variant_key=variant["key"],
                content=variant.get("content", {}).get(channel, variant.get("content", {})),
            )
            self.repo.add_message(msg)
            messages.append(msg)
        self.db.commit()

        # Try to enqueue to Redis; fall back to synchronous sending
        redis_client = _get_redis_client()
        if redis_client:
            try:
                enqueued = 0
                for message in messages[:limit]:
                    payload = {
                        "tenant_id": str(message.tenant_id),
                        "campaign_id": str(message.campaign_id),
                        "message_id": str(message.id),
                        "customer_id": str(message.customer_id),
                        "channel": message.channel,
                        "content": message.content if isinstance(message.content, dict) else {},
                    }
                    redis_client.rpush("campaign_messages", json.dumps(payload))
                    enqueued += 1
                logger.info("Enqueued %d messages to Redis queue 'campaign_messages'", enqueued)
            except Exception as exc:
                logger.warning("Redis enqueue failed, falling back to sync: %s", exc)
                for message in messages[:limit]:
                    self._send_to_provider(message, campaign)
        else:
            # Synchronous fallback
            for message in messages[:limit]:
                self._send_to_provider(message, campaign)

        self.repo.mark_running(campaign.id)
        return {"campaign_id": str(campaign.id), "queued": len(messages), "status": "running"}

    def schedule(self, campaign_id: uuid.UUID, scheduled_at: datetime) -> dict[str, Any]:
        """Schedule a campaign for future execution."""
        campaign = self.repo.get(campaign_id)
        if not campaign:
            raise ValueError("Campaign not found")
        campaign.scheduled_at = scheduled_at
        campaign.status = "scheduled"
        self.db.commit()
        return {
            "campaign_id": str(campaign.id),
            "status": "scheduled",
            "scheduled_at": scheduled_at.isoformat(),
        }

    @retry(wait=wait_exponential(multiplier=0.3, min=0.3, max=5), stop=stop_after_attempt(3))
    def _send_to_provider(self, message: Message, campaign: Campaign) -> None:
        payload = {
            "tenant_id": str(message.tenant_id),
            "campaign_id": str(message.campaign_id),
            "message_id": str(message.id),
            "customer_id": str(message.customer_id),
            "channel": message.channel,
            "content": message.content,
        }
        with httpx.Client(timeout=8) as client:
            response = client.post(f"{self.settings.channel_simulator_url}/provider/messages", json=payload)
            response.raise_for_status()
            body = response.json()
        message.provider_message_id = body["provider_message_id"]
        message.status = "sent"
        message.sent_at = datetime.now(timezone.utc)
        message.attempts += 1
        self.db.commit()

    def _coerce(self, value: Any) -> Any:
        if isinstance(value, str) and value.isdigit():
            return int(value)
        return value
